### ISSUE TITLE
Any plans to update this guide?

### ISSUE THREAD

**Issue by liuyocean** [spring-guides/gs-routing-and-filtering#16]
Hello there, since most of the Spring Cloud Netflix projects are in maintenance mode, package like `spring-cloud-netflix-zuul` can't be imported for newer version of Spring Boot.

Is there any plan to update this guide using Spring Cloud Gateway?

**Comment by ryanjbaxter** [comment]
There is a gateway guide here https://spring.io/guides/gs/gateway/
