### ISSUE TITLE
Gateway works for Brixton but does not work for Finchley.M1

### ISSUE THREAD

**Issue by TySequeira** [spring-guides/gs-routing-and-filtering#4]
Looks like Zuul is dead...

According to https://spring.io/blog/2017/07/06/spring-cloud-finchley-m1-is-available 

Spring Cloud Gateway
Spring Cloud Gateway is a new API Gateway based on Spring 5, Boot 2 and Project Reactor. It is viewed as a replacement for Zuul 1. Some features include:

Fine grained route predicates such as: path, host and HTTP method
Filters such as: path rewriting, adding headers and rate limiting
A Management API
A Route definition repository interface (for persisting route definitions).

**Comment by dsyer** [comment]
Zuul will continue to work in Finchley. It just isn't being evolved by Netflix. If this tutorial doesn't yet work when you upgrade directly that may be something you can fix. We don't usually upgrade the guides until the new releases are GA (out of milestones).
